# Generated by Django 5.0.6 on 2024-07-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "url",
                    models.URLField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="Summary"),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Content"),
                ),
                ("json", models.JSONField(blank=True, null=True, verbose_name="Json")),
                ("data", models.JSONField(blank=True, null=True, verbose_name="Data")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CrawlerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "url",
                    models.URLField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "title_pattern",
                    models.TextField(max_length=255, verbose_name="Title Pattern"),
                ),
                (
                    "summary_pattern",
                    models.TextField(
                        blank=True, null=True, verbose_name="Summary Pattern"
                    ),
                ),
                (
                    "content_pattern",
                    models.TextField(
                        blank=True, null=True, verbose_name="Content Pattern"
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True, verbose_name="Data")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
